// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkl9xTX-MtJPO0ghjDNQ0cfDChF6SqUHY',
    appId: '1:552257291650:web:b47df3c771bfb098243b9b',
    messagingSenderId: '552257291650',
    projectId: 'authentication-d8995',
    authDomain: 'authentication-d8995.firebaseapp.com',
    storageBucket: 'authentication-d8995.appspot.com',
    measurementId: 'G-YFXSLMMJE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjw8YKPCybkUSySrlRZcfkDEO3QyL960U',
    appId: '1:552257291650:android:91e1ac72edea4417243b9b',
    messagingSenderId: '552257291650',
    projectId: 'authentication-d8995',
    storageBucket: 'authentication-d8995.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_fN97PcCaWvW02J4jmssCP9UrUMTGUjY',
    appId: '1:552257291650:ios:640c9159bd0e74d7243b9b',
    messagingSenderId: '552257291650',
    projectId: 'authentication-d8995',
    storageBucket: 'authentication-d8995.appspot.com',
    iosBundleId: 'com.example.googleAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_fN97PcCaWvW02J4jmssCP9UrUMTGUjY',
    appId: '1:552257291650:ios:f45a87dafeb71b61243b9b',
    messagingSenderId: '552257291650',
    projectId: 'authentication-d8995',
    storageBucket: 'authentication-d8995.appspot.com',
    iosBundleId: 'com.example.googleAuthentication.RunnerTests',
  );
}
